### ISSUE TITLE
Is Stan a requirement to run this package?

### ISSUE THREAD

**Issue by usptact** [janezd/baycomp#1]
It appears that you use PyStan under the hood to perform hierarchical t-test (?). Is that true or is it simply an experimental feature that you still work on?

Anyways, thanks a lot for sharing this great package! Keep up good work!

**Comment by janezd** [comment]
No, it's not experimental, it's there to be used. It's just that PyStan requires C++ compiler, so it's not installed by default. It's not that difficult to manually install one additional package, and if it fails, `baycomp` is still useful. While if we make it a requirement and it, say, fails on Windows, the whole package doesn't install.

If you see a way around this, I'd be happy to include PyStan. Is there a way to tell setup.py to try to install a dependency, but ignore it if it fails?
