### ISSUE TITLE
New release on Pypi

### ISSUE THREAD

**Issue by sherbold** [janezd/baycomp#17]
Hi!

Thanks for this awesome lib. I use this downstream in a convenience-package for statistical analysis called autorank and a user suggested that we also make the Bayesian analysis reproducible with the random state (https://github.com/sherbold/autorank/issues/21). I think that is a great idea, and would like to expose this. However, I would like to avoid doing this by importing the current version directly from Github. 

Are there any plans to push a new release to Pypi? That would make this a lot easier for me :)

Best,
Steffen

**Comment by janezd** [comment]
Steffen, I can make a new release. But we have a more general problem here: I'm working on other projects and I've mostly forgotten about this package. A downstream user seems to be a good choice for a new maintainer. Would you be interested?

**Comment by sherbold** [comment]
I general, I would be honored Janez. But frankly, I am not sure that I would actually have more time than you have or that my understanding of the underlying Bayesian modelling is good enough to maintain this properly. 

For my autorank package I basically manage to squeeze in a couple of hours at the end of each teaching term and was lucky that this was sufficient for maintenance so far 🙃

**Comment by janezd** [comment]
I understand. Same here.

I uploaded a new release. Please report if I messed up anything.
