### ISSUE TITLE
Questions about baycomp.two_on_single

### ISSUE THREAD

**Issue by jmhessel** [janezd/baycomp#2]
Hi there! Thank you for the insightful work, and for the baycomp library! I had (what I hope) are a few quick clarification questions regarding `baycomp.two_on_single`.

In particular, I am in a scenario where I have computed accuracy of method A and method B over a single `k`-fold cross validation split on a single dataset -- for each algorithm, I have a vector of `k` performance metrics (`A[i]` and `B[i]`) where each value indicates the performance over the "test" split for a given algorithm over a given fold of the dataset (e.g., `A[3]` and `B[3]` give the performance according to some metric on the 3rd cross-validation fold). I am trying to decide whether performance differences I observe between A and B are likely to be meaningful or not.

I think that `baycomp.two_on_single` is the function I should be using. However -- the documentation was a bit confusing to me. In particular, the function requests "vectors of scores" for each model. I was a bit confused as to whether these vectors of scores correspond to performance over folds, or average scores over multiple cross-validations. In short -- is it okay to pass the length-k vectors `A[i]` and `B[i]` as input? And, if I were to run `m` multiple cross-validations, do I pass `m * k` length vectors to this function? And -- does the ordering of these values matter? If so -- what is the restriction on the ordering?

**Comment by janezd** [comment]
Yes, if you run k-fold cross validation for m times, you will pass two vectors of length `m * k`, not averages. The order doesn't matter, the only requirement is that the two vectors are aligned, that is, `A[i]` and `B[i]` must be measured on the same training and testing data.

If you repeat cross validations, don't forget to pass an argument `runs=m`.

**Comment by jmhessel** [comment]
Great! Thanks for the response, for your research, and for making this library!!! :)
