### ISSUE TITLE
How do i generate larger images?

### ISSUE THREAD

**Issue by henrique-voni** [janezd/baycomp#4]
Hello, 

I'm publishing a paper and i need to enlarge the results generated from my tests. I didn't find anything related in the docs.
Thanks.

**Comment by janezd** [comment]
What do you mean by "enlarge the results"?

**Comment by henrique-voni** [comment]
Sorry, i meant larger pictures. The two_on_single and two_on_multiple functions return 300x300px images.

**Comment by janezd** [comment]
Ooops, I read just the text, not the title. My bad.

These are matplotlib figures, so you can find detailed instructions for saving them in different formats and resolutions in the matplotlib documentation. I suppose [documentation about savefig](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.savefig) should help.

**Comment by henrique-voni** [comment]
The problem is that `two_on_multiple()` and `two_on_single()`  have a `plot` parameter that when is set to `True`, it returns the preset figure in default size. Should i customize these functions inside baycomp code perhaps?

**Comment by janezd** [comment]
Function does not set the size of the figure. If you use, for instance, `fig.savefig("name.png", dpi=576)`, you will get a pretty large figure.

**Comment by henrique-voni** [comment]
Thank you very much, i didn't realize that the test returned a tuple.
